# PostgreSQL Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5555/ave_caesar}
spring.datasource.username=${DATABASE_USER:avecaesar}
spring.datasource.password=${DATABASE_PASSWORD:Zelda214!}
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 Console OFF in production
spring.h2.console.enabled=false

# Validate schema in production
spring.jpa.hibernate.ddl-auto=validate

# Flyway ON for production
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


JWT_SECRET=aVeryLongSecretKeyThatIsAtLeast64BytesLongForHS512AlgorithmSecurityPurposesOnlyForDevelopment1234567890
JWT_EXPIRATION=86400000